services:
  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - collabathon-net


  backend:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MCP_SERVER_URL: ${MCP_SERVER_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - collabathon-net


  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - collabathon-net


  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8080:8081"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?sslmode=disable
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - collabathon-net


  mcp:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - collabathon-net


volumes:
  postgres_data:

networks:
  collabathon-net:
    driver: bridge