[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "psycopg2-binary>=2.9.9",
    "python-dotenv>=1.0.0",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "numpy<2.0.0"
]

[tool.poetry]
packages = [
    {include = "shared", from = "src"},
    {include = "backend", from = "src"},
    {include = "mcp_server", from = "src"}
]

[tool.poetry.scripts]
start = "backend.main:start"
dev = "backend.main:dev"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"